language: objective-c
before_install:
  - sudo easy_install cpp-coveralls
  - brew uninstall xctool
  - brew update
  - brew install xctool --HEAD  

script:
- xcodebuild clean test -sdk iphonesimulator -configuration Debug OBJROOT=build ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty

after_success:
  - coveralls -e Coveralls-iOS

env:
  global:
  - APPNAME="Coveralls-iOS"
