language: objective-c

before_install:
- chmod +x .utility/post_result.sh
- wget http://clang-analyzer.llvm.org/downloads/checker-276.tar.bz2
- tar -xvjf checker-276.tar.bz2
- svn checkout http://coverstory.googlecode.com/svn/trunk/ "$HOME/coverstory-read-only"

script:
- xcodebuild build -project $HOME/coverstory-read-only/CoverStory.xcodeproj CONFIGURATION_BUILD_DIR="/Applications"
- xcodebuild clean test -sdk iphonesimulator -project Coveralls-iOS.xcodeproj -scheme ci -configuration Debug OBJROOT=coverage_report ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
- ./checker-276/scan-build -o analyzer_report xcodebuild -sdk iphonesimulator clean analyze 

after_success:
- pwd
- ls coverage_report | sed "s;^;`pwd`;"
- .utility/post_result.sh

env:
  global:
    - APPNAME="Coveralls-iOS"
    - DESCRIPTION="Run test coverage and analyze"
    - secure: "GNH1xmul6peVsq+b7DIV1j0+A8udKptYoFIzwyJdP2US7gsZ3IWA8sB/Ox+0lBRouyM9eI8HMIYbxxA4v0c2xyJPEgfQe6PIr0QDsvETWJDrRel6fN6bkW6qiLE5AAjvphh5JGvOM8cLX3tpN94lTvQKS/hYCj+PsTer4kwKQt8="
