language: objective-c

before_install:
- chmod +x .utility/post_result.sh
- wget http://clang-analyzer.llvm.org/downloads/checker-276.tar.bz2
- tar -xvjf checker-276.tar.bz2

script:
- xcodebuild clean test -sdk iphonesimulator -project Coveralls-iOS.xcodeproj -scheme ci -configuration Debug OBJROOT=build ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
- ./checker-276/scan-build -o report xcodebuild -sdk iphonesimulator clean analyze 

after_success:
- .utility/post_result.sh

env:
  global:
  - APPNAME="Coveralls-iOS"
  - DESCRIPTION="Run test coverage and analyze"
  - secure: v45pjcogHNfXQyopD7gJRWHem9MeNqfViwSANlGBVt1XD5LgKqKlFKnLmq9HN8F+neUSwxGGYx/+sF8okLi5ax5qqNQVy5JsNLPtIYXbiu6MWhy8EZ77TogANu4VNk3/QfTx29Cin+XzU81W4wXsFQzE9KG71wGo1TtmI663Yxo=
  - secure: G5Iy28itMuVVKAYyLYCJ69Y62IQGz9c1Y4cmwjkvByP2CH+ylLb5vugMWk/DW/nheN93F2YKtdO3SuoKV06/GpVeFfHaHcHtEgHqbEGNzbtRuOmKCUJP7i3Rzu2FSMqkF4Y549ut9xqJg8yWi/9SKgWGEJfZR9H0E5/p8Y/7eKE=
