language: objective-c

before_install:
- chmod +x .utility/post_result.sh
- wget http://clang-analyzer.llvm.org/downloads/checker-276.tar.bz2
- tar -xvjf checker-276.tar.bz2

script:
- xcodebuild clean test -sdk iphonesimulator -project Coveralls-iOS.xcodeproj -scheme ci -configuration Debug OBJROOT=build ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
- ./checker-276/scan-build -o report xcodebuild -sdk iphonesimulator clean analyze 

after_success:
- .utility/post_result.sh

env:
  global:
  - APPNAME="Coveralls-iOS"
  - secure: "v45pjcogHNfXQyopD7gJRWHem9MeNqfViwSANlGBVt1XD5LgKqKlFKnLmq9HN8F+neUSwxGGYx/+sF8okLi5ax5qqNQVy5JsNLPtIYXbiu6MWhy8EZ77TogANu4VNk3/QfTx29Cin+XzU81W4wXsFQzE9KG71wGo1TtmI663Yxo="
  - secure: "RWHgGBE8Um6ceLPTqM/kYkVe0Y4jbuxGXK3SdgXB/qR5G0vz+aDQmHSlEcN+O/oaQ8dKtmk0u1RkmXlbPKYx0mynD81cjs3kg3+0vEg94qhj+pyQEgqWR2Aydb+KMRhpWf4gico+7Soei5Stdi841LZISU4nmVUyyH9z/cAu5iY="
