language: objective-c

before_install:
- chmod +x .utility/save_report.sh
- chmod +x .utility/coverage.sh
- chmod +x .utility/analyzer.sh

script:
- .utility/coverage.sh
- .utility/analyzer.sh

after_success:

env:
  global:
    - APPNAME="Coveralls-iOS"
    - DESCRIPTION="Run test coverage and analyze"
    # enviroment for report
    - REPORT_TOKEN="35636266373463666535653265396232363437393536396134633239616666326232366339393065"
    - COVERAGE_DIR="coverage_report"
    - ANALYZER_DIR="analyzer_report"
    - SLACK_CHANNEL="ci-report"
    #
    - secure: "v45pjcogHNfXQyopD7gJRWHem9MeNqfViwSANlGBVt1XD5LgKqKlFKnLmq9HN8F+neUSwxGGYx/+sF8okLi5ax5qqNQVy5JsNLPtIYXbiu6MWhy8EZ77TogANu4VNk3/QfTx29Cin+XzU81W4wXsFQzE9KG71wGo1TtmI663Yxo="
