language: objective-c

before_install:
- sudo easy_install cpp-coveralls
- gem install xcpretty
- wget http://clang-analyzer.llvm.org/downloads/checker-276.tar.bz2
- tar -xvjf checker-276.tar.bz2

script:
- xcodebuild clean test -sdk iphonesimulator -configuration Debug OBJROOT=build ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty
- ./checker-276/scan-build -o report xcodebuild -sdk iphonesimulator analyze 

after_success:
- ls report
- .utility/update-gh-pages.sh $GH_TOKEN
- ls /Users/travis/*
- coveralls -e checker-276
- brew -h
- sed -h

env:
  global:
  - APPNAME="Coveralls-iOS"
  - GH_TOKEN='14266bb42129ae71c1412dcf0d0623b46b580986'
