language: objective-c

before_install:
- chmod +x .utility/save_report.sh
- chmod +x .utility/coverage.sh
- chmod +x .utility/analyzer.sh

script:
# build coverage directory
- svn checkout http://coverstory.googlecode.com/svn/trunk/ "$HOME/coverstory-read-only"
- xcodebuild build -project $HOME/coverstory-read-only/CoverStory.xcodeproj CONFIGURATION_BUILD_DIR="/Applications"
- rm -rf "$HOME/coverstory-read-only"
- xcodebuild clean test -sdk iphonesimulator -project "$APPNAME.xcodeproj" -scheme ci -configuration Debug OBJROOT=$COVERAGE_DIR ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
- .utility/save_report.sh $REPORT_TOKEN "coverage"
- rm -rf $TRAVIS_BUILD_DIR/$COVERAGE_DIR
# - export COVERAGE_LINK=$coverage_link
# - export COVERAGE_REPOSITORY=$coverage_repository

# build analyzer directory
- wget http://clang-analyzer.llvm.org/downloads/checker-276.tar.bz2
- tar -xvjf checker-276.tar.bz2
- rm checker-276.tar.bz2
- ./checker-276/scan-build -o $ANALYZER_DIR xcodebuild -project "$APPNAME.xcodeproj" -configuration Debug -sdk iphonesimulator clean analyze 
- .utility/save_report.sh $REPORT_TOKEN "analyzer"
- rm -rf $TRAVIS_BUILD_DIR/$ANALYZER_DIR
# - export ANALYZER_LINK=$analyzer_link
# - export ANALYZER_REPOSITORY=$analyzer_repository

after_success:
- .utility/save_report.sh $REPORT_TOKEN "send_message"

env:
  global:
    - APPNAME="Coveralls-iOS"
    - DESCRIPTION="Run test coverage and analyze"
    # enviroment for report
    - REPORT_TOKEN="35636266373463666535653265396232363437393536396134633239616666326232366339393065"
    - COVERAGE_DIR="coverage_report"
    - ANALYZER_DIR="analyzer_report"
    - SLACK_CHANNEL="ci-report"
    #
    - secure: "v45pjcogHNfXQyopD7gJRWHem9MeNqfViwSANlGBVt1XD5LgKqKlFKnLmq9HN8F+neUSwxGGYx/+sF8okLi5ax5qqNQVy5JsNLPtIYXbiu6MWhy8EZ77TogANu4VNk3/QfTx29Cin+XzU81W4wXsFQzE9KG71wGo1TtmI663Yxo="
